/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./components/**/*.{js,vue,ts}",
    "./layouts/**/*.vue",
    "./pages/**/*.vue",
    "./plugins/**/*.{js,ts}",
    "./app.vue",
    "./error.vue",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#410000",
        "on-surface-variant": "#414751",
        "on-primary-fixed": "#001c39",
        "primary-container": "#3176c3",
        "on-tertiary-fixed-variant": "#7f2920",
        "background": "#f6fafd",
        "tertiary-container": "#bb5548",
        "on-secondary-fixed-variant": "#005045",
        "secondary-fixed": "#a4f1df",
        "surface-bright": "#f6fafd",
        "surface-tint": "#075fab",
        "secondary-fixed-dim": "#89d5c4",
        "inverse-on-surface": "#edf1f4",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-secondary-container": "#1e7062",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f4f7",
        "on-secondary": "#ffffff",
        "primary": "#005da9",
        "surface-variant": "#dfe3e6",
        "error-container": "#ffdad6",
        "tertiary": "#9b3e32",
        "surface-container-high": "#e5e9ec",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#a4c9ff",
        "on-surface": "#171c1f",
        "on-tertiary": "#ffffff",
        "secondary-container": "#a4f1df",
        "outline": "#717783",
        "inverse-surface": "#2c3134",
        "on-background": "#171c1f",
        "on-primary-container": "#fdfcff",
        "on-primary-fixed-variant": "#004884",
        "inverse-primary": "#a4c9ff",
        "on-secondary-fixed": "#00201b",
        "surface-container": "#eaeef1",
        "on-error-container": "#93000a",
        "surface": "#f6fafd",
        "error": "#ba1a1a",
        "tertiary-fixed": "#ffdad5",
        "surface-container-highest": "#dfe3e6",
        "outline-variant": "#c1c7d3",
        "on-tertiary-container": "#fffbff",
        "secondary": "#146a5c",
        "surface-dim": "#d6dbdd",
        "primary-fixed": "#d4e3ff",
        "on-error": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Lexend", "sans-serif"],
        "label": ["Lexend", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
